/* eslint-disable react/prop-types */
import { Bird, Cat, Dog, Fish, Hamster, PetAccessories, PetBedding, PetClothing, PetFood, PetGrooming, PetHealthcare, PetToys, Rabbit } from "../assets";

const petCategories = [
  {
    id: 1,
    name: "Dogs",
    img: Dog,
  },
  {
    id: 2,
    name: "Cats",
    img: Cat,
  },
  {
    id: 3,
    name: "Fish",
    img: Fish,
  },
  {
    id: 4,
    name: "Birds",
    img: Bird,
  },
  {
    id: 5,
    name: "Rabbits",
    img: Rabbit,
  },
  {
    id: 6,
    name: "Hamster",
    img: Hamster,
  },
];


const FavouriteProductData = [
  {
    id: 1,
    productImg: Hamster,
    productName: "Hamster",
    shopName: "Achievers",
    category: ["Clothing", "Food", "Toys"],
    price: 5000,
    rating: "3.8 / 5",
  },
  {
    id: 2,
    productImg: Hamster,
    productName: "Hamster",
    shopName: "Achievers",
    category: ["Clothing", "Food", "Toys"],
    price: 5000,
    rating: "3.8 / 5",
  },
  {
    id: 3,
    productImg: Hamster,
    productName: "Hamster",
    shopName: "Achievers",
    category: ["Clothing", "Food", "Toys"],
    price: 5000,
    rating: "3.8 / 5",
  },
  {
    id: 4,
    productImg: Hamster,
    productName: "Hamster",
    shopName: "Achievers",
    category: ["Clothing", "Food", "Toys"],
    price: 5000,
    rating: "3.8 / 5",
  },
  {
    id: 5,
    productImg: Hamster,
    productName: "Hamster",
    shopName: "Achievers",
    category: ["Clothing", "Food", "Toys"],
    price: 5000,
    rating: "3.8 / 5",
  },
  {
    id: 6,
    productImg: Hamster,
    productName: "Hamster",
    shopName: "Achievers",
    category: ["Clothing", "Food", "Toys"],
    price: 5000,
    rating: "3.8 / 5",
  },
  {
    id: 7,
    productImg: Hamster,
    productName: "Hamster",
    shopName: "Achievers",
    category: ["Clothing", "Food", "Toys", "Toys", "Toys", "Toys"],
    price: 5000,
    rating: "3.8 / 5",
  },
];

const marketplaceCategories = [
  {
    id: 1,
    name: "Pet Food",
    tag:"petFood",
    img: PetFood,
  },
  {
    id: 2,
    name: "Grooming",
    tag:"grooming",
    img: PetGrooming,
  },
  {
    id: 3,
    name: "Toys",
    tag:"toys",
    img: PetToys,
  },
  {
    id: 4,
    name: "Bedding",
    tag:"bedding",
    img: PetBedding,
  },
  {
    id: 5,
    name: "Healthcare",
    tag:"healthcare",
    img: PetHealthcare,
  },
  {
    id: 6,
    name: "Clothing",
    tag:"clothing",
    img: PetClothing,
  },
  {
    id: 7,
    name: "Accessories",
    tag:"accessories",
    img: PetAccessories,
  },
];

const ShopPetData = [
  {
    id: 1,
    petImg: Hamster,
    petName: "Hamster",
    category:"Dogs",
    petAge: "2 year",
    price: 2000,
  },
  {
    id: 1,
    petImg: Hamster,
    petName: "Hamster",
    category:"Dogs",
    petAge: "2 year",
    price: 1000,
  },
  {
    id: 2,
    petImg: Hamster,
    petName: "Hamster",
    category:"Dogs",
    petAge: "2 year",
    price: 500,
  },
  {
    id: 3,
    petImg: Hamster,
    petName: "Hamster",
    category:"Dogs",
    petAge: "2 year",
    price: 2000,
  },
  {
    id: 4,
    petImg: Hamster,
    petName: "Hamster",
    category:"Dogs",
    petAge: "2 year",
    price: 2000,
  },
  {
    id: 5,
    petImg: Hamster,
    petName: "Cat",
    category:"Dogs",
    petAge: "2 year",
    price: 3000,
  },
  {
    id: 6,
    petImg: Hamster,
    petName: "Hamster",
    category:"Dogs",
    petAge: "2 year",
    price: 2000,
  },
  {
    id: 7,
    petImg: Hamster,
    petName: "Hamster",
    category:"Dogs",
    petAge: "2 year",
    price: 2000,
  },
  {
    id: 8,
    petImg: Hamster,
    petName: "Hamster",
    category:"Dogs",
    petAge: "2 year",
    price: 2000,
  },
  {
    id: 9,
    petImg: Hamster,
    petName: "Hamster",
    category:"Dogs",
    petAge: "2 year",
    price: 2000,
  },
  {
    id: 10,
    petImg: Hamster,
    petName: "Hamster",
    category:"Dogs",
    petAge: "2 year",
    price: 2000,
  },
];

const statesArray = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Lakshadweep",
  "Puducherry",
  "Ladakh",
]

const shopOrderData = [
  {
    id: 1,
    Date: "new Date",
    Customer: "Arman",
    Payment:"pending",
    Total: 5000,
    Location: "Boisar",
    Items:5,
    Status:"success",
    UserProfilePic:"https://github.com/shadcn.png",
    ProfileFallback:"BG"
  },
  {
    id: 2,
    Date: "new Date",
    Customer: "Arman",
    Payment:"pending",
    Total: 5000,
    Location: "Boisar",
    Items:5,
    Status:"success",
    UserProfilePic:"https://github.com/shadcn.png",
    ProfileFallback:"BG"
  },
  {
    id: 3,
    Date: "new Date",
    Customer: "Arman",
    Payment:"pending",
    Total: 5000,
    Location: "Boisar",
    Items:5,
    Status:"success",
    UserProfilePic:"https://github.com/shadcn.pngdfd",
    ProfileFallback:"BG"
  },
  {
    id: 4,
    Date: "new Date",
    Customer: "Arman",
    Payment:"pending",
    Total: 5000,
    Location: "Boisar",
    Items:5,
    Status:"success",
    UserProfilePic:"https://github.com/shadcn.png",
    ProfileFallback:"BG"
  },
  {
    id: 5,
    Date: "new Date",
    Customer: "Imran",
    Payment:"pending",
    Total: 5000,
    Location: "Boisar",
    Items:5,
    Status:"success",
    UserProfilePic:"https://github.com/shadcn.png",
    ProfileFallback:"BG"
  },
  {
    id: 6,
    Date: "new Date",
    Customer: "Arman",
    Payment:"pending",
    Total: 5000,
    Location: "Boisar",
    Items:5,
    Status:"success",
    UserProfilePic:"https://github.com/shadcn.png",
    ProfileFallback:"BG"
  },
  {
    id: 7,
    Date: "new Date",
    Customer: "Arman",
    Payment:"pending",
    Total: 5000,
    Location: "Boisar",
    Items:5,
    Status:"success",
    UserProfilePic:"https://github.com/shadcn.png",
    ProfileFallback:"BG"
  },
  {
    id: 8,
    Date: "new Date",
    Customer: "Arman",
    Payment:"pending",
    Total: 5000,
    Location: "Boisar",
    Items:5,
    Status:"success",
    UserProfilePic:"https://github.com/shadcn.png",
    ProfileFallback:"BG"
  },
]

const orderItems = [
  {
    name: "MacBook Pro 14\u201d",
    description: "Space Gray | 32GB | 1 TB",
    price: "$2599.00",
    quantity: 1,
    image: "/path-to-macbook-image.jpg",
  },
  {
    name: "iPad Pro 12.9\u201d",
    description: "Space Gray | 2TB | Cellular",
    price: "$2399.00",
    quantity: 1,
    image: "/path-to-ipad-image.jpg",
  },
  {
    name: "AirPods Max",
    description: "Space Gray",
    price: "$549.00",
    quantity: 1,
    image: "/path-to-airpods-image.jpg",
  },
  {
    name: "AirPods Max",
    description: "Space Gray",
    price: "$549.00",
    quantity: 1,
    image: "/path-to-airpods-image.jpg",
  },
  {
    name: "AirPods Max",
    description: "Space Gray",
    price: "$549.00",
    quantity: 1,
    image: "/path-to-airpods-image.jpg",
  },
  {
    name: "AirPods Max",
    description: "Space Gray",
    price: "$549.00",
    quantity: 1,
    image: "/path-to-airpods-image.jpg",
  },
  {
    name: "AirPods Max",
    description: "Space Gray",
    price: "$549.00",
    quantity: 1,
    image: "/path-to-airpods-image.jpg",
  },
  {
    name: "AirPods Max",
    description: "Space Gray",
    price: "$549.00",
    quantity: 1,
    image: "/path-to-airpods-image.jpg",
  },
  {
    name: "AirPods Max",
    description: "Space Gray",
    price: "$549.00",
    quantity: 1,
    image: "/path-to-airpods-image.jpg",
  },
];

export {
  petCategories,
  FavouriteProductData,
  marketplaceCategories,
  ShopPetData,
  statesArray,
  shopOrderData,
  orderItems,
};
